[build]
# Build command — first runs tsc, then Vite build
command = "npm run build"

# Folder to publish — Vite outputs to dist by default
publish = "dist"

# For SPA: redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
